### ISSUE TITLE
crash after login and select any profile

### ISSUE THREAD

**Issue by ktullanux** [birdieapp/birdie#171] opened 2016-02-07 14:37 UTC
birdie --debug                                      
[_LEVEL_WARN 17:33:42.533040] [GLib-GObject] /build/buildd/glib2.0-2.42.2/./gobject/gsignal.c:2361: signal 'edge-reached' is invalid for instance '0x1c95570' of type 'GtkScrolledWindow'
[_LEVEL_WARN 17:33:42.533616] [GLib-GObject] /build/buildd/glib2.0-2.42.2/./gobject/gsignal.c:2361: signal 'edge-reached' is invalid for instance '0x1c95740' of type 'GtkScrolledWindow'
[_LEVEL_WARN 17:33:42.537142] [GLib-GObject] /build/buildd/glib2.0-2.42.2/./gobject/gsignal.c:2361: signal 'edge-reached' is invalid for instance '0x1ce3830' of type 'GtkScrolledWindow'
[_LEVEL_FATAL 17:33:53.423723] [Gtk] gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed
[_LEVEL_FATAL 17:33:53.423984] birdie will not function properly.
[_LEVEL_FATAL 17:33:53.424213] [Gtk] gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed
[_LEVEL_FATAL 17:33:53.424238] birdie will not function properly.
[_LEVEL_FATAL 17:33:53.424266] [Gtk] gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed
[_LEVEL_FATAL 17:33:53.424307] birdie will not function properly.
[_LEVEL_FATAL 17:33:53.424373] [Gtk] gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed
[_LEVEL_FATAL 17:33:53.424394] birdie will not function properly.
[_LEVEL_FATAL 17:33:53.424421] [Gtk] gtk_container_remove: assertion 'GTK_IS_CONTAINER (container)' failed
[_LEVEL_FATAL 17:33:53.424438] birdie will not function properly.
[1]    8183 segmentation fault (core dumped)  birdie --debug

**Comment by nathandyer** [comment] 2016-05-31 16:04
Thanks for your bug report! As far as I can tell, this is a duplicate of issue #181.

**Closed by nathandyer** 2016-05-31 16:04 UTC
