### ISSUE TITLE
There is no vertical blinkie cursor in the new tweet editor

### ISSUE THREAD

**Issue by bgcarlisle** [birdieapp/birdie#176] opened 2016-02-08 19:49 UTC
When I reply or start a new tweet, there is no visible cursor

**Comment by nathandyer** [comment] 2016-05-29 18:51
Thanks for your report, but I'm going to close this issue because it is a duplicate of #166. Please refer to that issue to see progress as it is made. Cheers!

**Closed by nathandyer** 2016-05-29 18:51 UTC
